INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (69, ' Faire', 'Wolf, Gita', 'Rue du monde', 281, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (145, ' Bonsoir Lune', 'Wise Brown, Margaret ', 'Lécole des loisirs', 470, false);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (250, ' Lours et le chat sauvage', 'Yumoto, Kasumi', 'Lécole des loisirs', 493, false);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (249, ' Drôle doiseau', 'Yerkes, Jennifer', 'MeMo', 456, false);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (248, ' Guili Lapin', 'Willems, Mo', 'Kaléidoscope', 426, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (247, ' Le bonnet rouge (album)', 'Weninger, Brigitte', 'Minedition', 387, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (194, ' Chut, chut, Charlotte !', 'Wells, Rosemary', 'Gallimard jeunesse', 425, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (68, ' Les petits bonheurs du pré', 'Weiss, Anne', 'Mila', 318, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (112, ' Hum-Hum', 'Wegerif, Gay', 'MeMo', 472, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (246, ' John Brown, Rose et le chat de minuit', 'Wagner, Jenny', 'Âne bâté (Il était deux fois)', 211, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (193, ' Bébés chouettes', 'Wadell, Martin ', 'Kaléidoscope', 186, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (67, ' Pourquôôââ', 'Voutch', 'Thierry Magnier', 312, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (192, ' Toujours rien ?', 'Voltz, Christian', 'Rouergue', 229, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (191, ' Bienvenue Tigrou !', 'Voake, Charlotte', 'Gallimard jeunesse', 264, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (245, ' Noël chez Ernest et Célestine', 'Vincent, Gabrielle', 'Casterman', 188, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (144, ' Petite graine', 'Vernette, Véronique', 'Points de suspension', 491, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (190, ' Coffret "4 histoires dAmir"', 'Vaugelade, Anaïs', 'Lécole des loisirs', 152, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (244, ' Petit à petit', 'Vast, Émilie', 'MeMo', 388, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (243, ' Cest à moi, ça !', 'Van Zeveren, Michel', 'Lécole des loisirs', 395, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (242, ' Mauvais temps', 'Van Reek, Wouter', 'Bayard jeunesse', 237, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (143, ' Le beau ver dodu', 'Van Laan, Nancy', 'Kaléidoscope', 327, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (66, ' Aujourdhui, je suis…', 'Van Hout, Mies', 'Minedition', 487, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (241, ' La chaussette verte de Lisette', 'Valckx, Catharina ', 'Lécole des loisirs', 131, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (240, ' Les trois brigands', 'Ungerer, Tomi', 'Lécole des loisirs', 214, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (111, ' Un livre', 'Tullet, Hervé', 'Bayard jeunesse', 117, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (189, ' Le gros navet', 'Tolstoï, Alekseï', 'Flammarion - Père-Castor', 477, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (188, ' Barbapapa ', 'Tison, Annette et Taylor, Talus', 'Livres du Dragon  dor', 114, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (142, ' La tarte aux pommes de papa', 'Thompson, Lauren', 'Seuil jeunesse', 333, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (65, ' Comptine', 'Tardieu, Jean', 'Rue du monde', 389, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (239, ' La lettre du Père Noël', 'Tanno, Yukiko', 'Lécole des loisirs', 294, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (110, ' À qui est ce vélo ?', 'Takabatake, Jun', 'Picquier jeunesse', 335, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (64, ' La maison dans la nuit', 'Swanson, Susan-Marie', 'Le Genévrier', 242, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (109, ' Drôle de pizza', 'Steig, William', 'Kaléidoscope', 348, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (141, ' Coin-Coin', 'Stehr, Frédéric', 'Lécole des loisirs', 101, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (63, ' Les animaux ont la parole', 'Spier, Peter', 'Lécole des loisirs', 373, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (140, ' Amour-caillou', 'Solotareff, Grégoire', 'Lécole des loisirs', 356, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (187, ' À tout petits pas', 'Simon, James', 'Gautier-Languereau', 317, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (17, ' Les vingt contes les plus drôles du monde', 'Sierra, Judy', 'Gallimard jeunesse', 415, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (238, ' Il neige', 'Shulevitz, Uri', 'Kaléidoscope', 403, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (108, ' À quoi ça rime ? - Laventure dun nain malin', 'Shibuya, Junko', 'Autrement jeunesse', 392, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (62, ' Petits', 'Serres, Alain', 'Rue du monde', 473, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (107, ' Maman ?', 'Sendak, Maurice', 'Lécole des loisirs', 319, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (61, ' Les douze manteaux de maman', 'Sellier, Marie', 'Le baron perché', 262, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (237, ' La grande peur de Mariette et Soupir', 'Schwartz, Irène', 'Lécole des loisirs', 104, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (186, ' Le parapluie', 'Schubert, Ingrid et Dieter', 'Mijade', 483, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (60, ' Lalphabet zinzin', 'Sazonoff, Zazie', 'Mila', 340, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (139, ' Éléphants', 'Sara', 'Thierry Magnier', 251, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (185, ' Non !', 'Rueda, Claudia', 'Rue du monde', 244, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (59, ' Lenfant quon envoie se coucher', 'Roy, Claude', 'Rue du monde', 432, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (236, ' Je veux mon ptit pot !', 'Ross, Tony', 'Gallimard jeunesse', 475, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (138, ' 100 aventures de mimi cracra', 'Rosenstiehl, Agnès', 'Seuil jeunesse', 264, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (106, ' La chasse à lours', 'Rosen, Michael ', 'Kaléidoscope', 270, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (58, ' Il faut une fleur', 'Rodari, Gianni', 'Rue du monde', 204, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (184, ' Trois petits pois', 'Rivoal, Marine', 'Rouergue', 188, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (195, ' La maison à dormir debout', 'Wood, Audrey', 'Mijade', 156, false);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (235, ' Une toute petite, petite fille', 'Rener, Raymond', 'Gallimard jeunesse', 177, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (57, ' Un, deux, trois… dans larbre !', 'Ravishankar, Anita', 'Actes Sud junior', 347, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (105, ' Le vent ma pris', 'Rascal', 'Pastel', 273, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (104, ' Tout en haut', 'Ramos, Mario', 'Lécole des loisirs', 468, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (56, ' Un ogre', 'Ramadier, Cédric', 'Lécole des loisirs', 173, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (16, ' Jeux de doigts, jeux de rois', 'Quinta, Philippe', 'Soc et Foc', 345, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (183, ' Les trois petits pourceaux', 'Promeyrat, Coline', 'Didier jeunesse', 365, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (15, ' Pierre et le loup (avec Cédé)', 'Prokofiev, Serge', 'Gallimard jeunesse', 328, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (14, ' En sortant de lécole ', 'Prévert, Jacques', 'Gallimard jeunesse', 401, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (182, ' Par une nuit très, très sombre', 'Prescott, Simon', 'Minedition', 100, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (137, ' Mon pull', 'Poussier, Audrey', 'Lécole des loisirs', 104, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (234, ' Pierre Lapin', 'Potter, Beatrix', 'Gallimard jeunesse', 104, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (55, ' Lalbum dAdèle', 'Ponti, Claude', 'Gallimard jeunesse', 325, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (54, ' Les contraires', 'Pittau et Gervais', 'Seuil jeunesse', 351, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (103, ' La maison hantée', 'Pienkowski, Jan', 'Nathan', 178, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (233, ' Le petit chaperon rouge ', 'Perrault, Charles ', 'Gallimard jeunesse', 499, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (232, ' Rendez-moi mes poux !', 'Pef', 'Gallimard jeunesse', 277, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (136, ' Mes petites choses', 'Park, Hyun-Jung', 'Chan-ok', 396, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (53, ' Alphabet', 'Pacovská, Kv?ta', 'Minedition', 369, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (181, ' Faites la queue !', 'Ohmura, Tomoko', 'Lécole des loisirs', 459, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (231, ' Bêtes', 'Negrin, Fabian', 'Seuil jeunesse', 367, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (180, ' Petit chat perdu', 'Natacha', 'Flammarion - Père-Castor', 146, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (135, ' Ne bouge pas !', 'Nakawaki, Hatsue', 'Lécole des loisirs', 338, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (134, ' Il faut sauver le petit chat !', 'Nakagawa, Chihiro', 'Rue du monde', 201, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (102, ' Deux mains deux petits chiens', 'Nadja', 'Lécole des loisirs', 471, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (52, ' Bébés animaux de A à Z', 'Murphy, Chuck', 'Gautier-Languereau', 147, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (230, ' Boucles dOr et les trois ours', 'Muller, Gerda', 'Lécole des loisirs', 496, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (133, ' Pas', 'Morgenstern, Susie', 'Rouergue', 417, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (13, ' Les histoires des trois petits cochons racontées dans le monde', 'Morel, Fabienne et Bizouerne, Gilles (recueillies par)', 'Syros', 187, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (101, ' À la rencontre', 'Morel, Claudine', 'Didier jeunesse', 315, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (12, ' Contes ritournelles', 'Montelle, Édith', 'Gulf stream', 374, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (100, ' Cache Cache', 'Monsieuroff', 'Atelier du Poisson soluble', 360, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (179, ' La carotte géante', 'Mets, Alan', 'Lécole des loisirs', 357, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (229, ' Lécureuil et la première neige', 'Meschenmoser, Sebastian', 'Minedition', 325, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (178, ' Elmer', 'McKee, David', 'Kaléidoscope', 378, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (228, ' Laissez passer les canards', 'McCloskey, Robert', 'Circonflexe', 170, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (177, ' Il y a un cauchemar dans mon placard', 'Mayer, Mercer', 'Gallimard jeunesse', 378, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (51, ' Une poule', 'Maubille, Jean', 'Lécole des loisirs', 463, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (176, ' Le petit poussin rouge', 'Matthews, Tina', 'Circonflexe', 280, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (99, ' Et pourquoi pas toi ?', 'Matoso, Madalena', 'Notari', 180, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (175, ' Du bruit sous le lit', 'Mathis, Jean-Marc', 'Thierry Magnier', 500, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (174, ' À bras ! Abracadabra', 'Martha', 'Atelier du Poisson soluble', 341, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (98, ' Les aventures dune petite bulle rouge', 'Mari, Iela', 'Lécole des loisirs', 269, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (227, ' Bébé', 'Manuschkin, Fran', 'Lécole des loisirs', 372, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (97, ' Merci le vent', 'Manceau,  Édouard', 'Milan jeunesse', 223, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (11, ' Virelangues (avec Cédé)', 'Maillet, Béatrice', 'Enfance et musique', 285, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (50, ' Le coq qui faisait coquelicot', 'Madeléna, Arnaud', 'La joie de lire', 334, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (96, ' La promenade de Flaubert', 'Louchard, Antonin', 'Thierry Magnier', 305, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (226, ' Porculus', 'Lobel, Arnold', 'Lécole des loisirs', 130, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (49, ' Encore un quart dheure', 'Lison-Leroy, Françoise et Nys-Mazure, Colette', 'Esperluète', 490, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (173, ' Petit-Bleu et Petit-Jaune', 'Lionni, Leo', 'Lécole des loisirs', 398, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (172, ' La maman et le bébé terrible', 'Lindgren, Barbro', 'Mijade', 250, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (225, ' Poule rousse', 'Lida', 'Flammarion - Père-Castor', 121, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (224, ' En attendant maman', 'Lee Tae-Jun', 'Didier jeunesse', 449, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (132, ' La boîte des papas 3 ', 'Le Saux, Alain', 'Lécole des loisirs', 210, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (48, ' Un Bois', 'Le Bec, Gwendal', 'Albin Michel jeunesse', 398, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (47, ' Qui suis-je ?', 'Lanchais, Aurélie', 'Seuil jeunesse', 456, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (95, ' Cest comme ça chez moi', 'Laffon, Martine', 'Thierry Magnier', 464, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (46, ' Un ours comme ci, un ours comme ça', 'Krolak, Agata', 'Rue du monde', 225, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (223, ' Anton et la feuille', 'Könnecke, Ole', 'Lécole des loisirs', 181, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (222, ' Toc, toc, toc', 'Koide, Tan', 'Lécole des loisirs', 368, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (171, ' À la sieste, tout le monde !', 'Kasano, Yuichi', 'Lécole des loisirs', 331, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (131, ' Mer bleue', 'Kalan, Robert', 'Kaléidoscope', 367, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (130, ' Où est Maman Ourse ?', 'Jonas, Ann', 'Didier jeunesse', 430, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (94, ' Zoo logique', 'Jolivet, Joëlle', 'Seuil jeunesse', 420, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (170, ' Nénette la grenouille verte', 'Janvier, Cédric', 'Balivernes', 384, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (221, ' Le cinquième', 'Jandl, Ernst', 'Lécole des loisirs', 331, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (129, ' Juste un petit bout !', 'Jadoul, Émile', 'Lécole des loisirs', 325, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (128, ' La pomme rouge', 'Iwamura, Kazuo', 'Lécole des loisirs', 438, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (10, ' Ohé ! Les comptines du monde entier !', 'Ivanovitch-Lair, Albena (réunies par)', 'Rue du monde ', 257, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (127, ' Tout va bien Merlin !', 'Houdart, Emmanuelle', 'Thierry Magnier', 405, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (9, ' Blanc, le petit chaton - version française (kamishibaï)', 'Horio, Seishi', 'Dôshinsha', 273, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (169, ' De la petite taupe qui voulait savoir qui lui avait fait sur la tête', 'Holzwarth, Werner', 'Milan jeunesse', 238, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (93, ' Regarde bien', 'Hoban, Tana', 'Kaléidoscope', 420, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (45, ' Chuuut! ', 'Ho, Minfong', 'Flammarion - Père-Castor', 305, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (8, ' Comptines pour doigts et menottes (avec Cédé)', 'Hion, Monique', 'Actes Sud junior', 117, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (92, ' Où est Spot, mon petit chien ?', 'Hill, Éric', 'Nathan', 213, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (168, ' Encore un bisou !', 'Hest, Amy', 'Albin Michel jeunesse', 393, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (44, ' Que fait la lune la nuit ?', 'Herbauts, Anne', 'Casterman', 471, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (220, ' Trois amis', 'Heine, Helme', 'Gallimard jeunesse', 292, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (126, ' Moi, Milton', 'Haydé', 'La joie de lire', 203, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (125, ' Un peu perdu', 'Haughton, Chris', 'Thierry Magnier', 346, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (124, ' Montre-moi !', 'Hall Ets, Marie', 'Lécole des loisirs', 444, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (167, ' Cours !', 'Haery, Lee', 'La joie de lire', 403, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (91, ' Pénélope se déguise', 'Gutman, Anne', 'Gallimard jeunesse', 142, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (219, ' Prédateurs', 'Guilloppé, Antoine', 'Thierry Magnier', 491, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (166, ' Le papa qui avait 10 enfants', 'Guettier, Bénédicte', 'Casterman', 294, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (218, ' Les aventures dItamar', 'Grossman, David', 'Seuil jeunesse', 317, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (43, ' Pour grandir, il faut…', 'Grive, Catherine', 'Rouergue', 262, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (90, ' Chhht !', 'Grindley, Sally', 'Pastel', 291, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (217, ' Le petit chaperon rouge', 'Grimm, Jacob et Wilhelm ', 'Magnard jeunesse', 208, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (123, ' Oups !', 'Gréban, Quentin', 'Mijade', 496, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (165, ' Drôle dœuf', 'Gravett, Emily', 'Kaléidoscope', 451, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (89, ' Le mille-pattes', 'Gourounas, Jean', 'Rouergue', 272, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (164, ' Matty et les cent méchants loups', 'Gorbachev, Valeri', 'Mijade', 176, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (88, ' Où est passé papa ?', 'Gomi, Taro', 'Autrement jeunesse', 302, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (87, ' Oh !', 'Goffin, Josse', 'Réunion des Musées Narionaux', 175, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (163, ' Brise Cabane', 'Giraud, Robert', 'Flammarion - Père-Castor', 437, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (86, ' Un...papillon sur un chapeau', 'Gibert, Bruno', 'Autrement jeunesse', 106, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (122, ' Quel radis dis donc!', 'Gay-Para, Praline ', 'Didier jeunesse', 491, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (121, ' Le coffret "Petit-camion, Petit-bateau, Petit-avion"', 'Gay, Michel', 'Lécole des loisirs', 260, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (7, ' Mon petit doigt ma dit', 'Galodé, Catherine', 'Alice jeunesse', 141, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (216, ' Poule Plumette', 'Galdone, Paul', 'Circonflexe', 115, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (162, ' La disparition', 'Frasson-Cochet, Agathe', 'MeMo', 475, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (215, ' La grande panthère noire', 'François, Paul', 'Flammarion - Père-Castor', 458, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (42, ' 2 petites mains et 2 petits pieds', 'Fox, Mem', 'Gallimard jeunesse', 374, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (161, ' Ne tinquiète pas, Petit Ours', 'Foley, Greg', 'Circonflexe', 454, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (41, ' 2 yeux ?', 'Félix, Lucie', 'Les grandes personnes', 158, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (160, ' Aboie, Georges !', 'Feiffer, Jules', 'Lécole des loisirs', 456, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (40, ' Nappe comme neige', 'Fayolle, Marion', 'Notari', 160, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (159, ' Aquarium', 'Fastier, Yann', 'Atelier du poisson soluble', 366, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (158, ' Bonjour Docteur', 'Escoffier, Michaël', 'Lécole des loisirs', 350, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (39, ' Les dix petits harengs', 'Erlbruch, Wolf', 'La joie de lire', 340, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (85, ' Va-t-en, grand monstre vert !', 'Emberley, Ed', 'Kaléidoscope', 334, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (157, ' Clown', 'Elzbieta', 'Lécole des loisirs', 329, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (156, ' Petit Clown, le trou', 'Duquennoy, Jacques', 'Albin Michel jeunesse', 257, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (120, ' Lola', 'Dunrea, Olivier', 'Kaléidoscope', 226, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (84, ' Loup ', 'Douzou, Olivier', 'Rouergue', 288, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (83, ' Ce livre-là', 'Doray, Malika', 'MeMo', 380, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (6, ' Le jour où le soleil a disparu (Théâtre dombres)', 'Dieterlé, Nathalie', 'Casterman', 215, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (38, ' Au pied de ma lettre…', 'Deverson-Otwinoski, Virginie', 'Millepages', 446, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (155, ' Le Griffognac contre le Grobidum', 'Dedieu, Thierry', 'Gallimard jeunesse', 308, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (37, ' Ouvre les yeux !', 'Dé, Claire', 'Les grandes personnes', 339, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (154, ' Cest lhistoire dun éléphant…', 'De Lestrade, Agnès', 'Sarbacane', 405, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (82, ' 1, 2, 3 Qui est là ?', 'De Greef, Sabine', 'Pastel', 345, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (214, ' Lénorme crocodile', 'Dahl, Roald', 'Gallimard jeunesse', 470, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (153, ' Le chat et le poisson', 'Dahan, André ', 'Mijade', 173, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (36, ' En voiture !', 'Cumont, Louise-Marie', 'MeMo', 442, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (213, ' Alors ?', 'Crowther, Kitty', 'Pastel', 292, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (35, ' Un train passe', 'Crews, Donald', 'Âne bâté (Il était deux fois)', 150, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (34, ' Raymond rêve', 'Crausaz, Anne ', 'MeMo', 176, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (119, ' Mimi va nager', 'Cousins, Lucy', 'Albin Michel jeunesse', 183, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (152, ' Tchoupi se perd au supermarché', 'Courtin, Thierry', 'Nathan', 141, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (33, ' Tout un monde', 'Couprie, Katy', 'Thierry Magnier', 386, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (81, ' Le livre noir des couleurs', 'Cottin, Menena et Faria, Rosana', 'Rue du monde', 472, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (212, ' Les deux goinfres', 'Corentin, Philippe', 'Lécole des loisirs', 316, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (32, ' Chaussettes', 'Corazza, Lynda', 'Rouergue', 431, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (211, ' Très, très fort !', 'Cooke, Trish', 'Flammarion - Père-Castor', 260, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (210, ' Marlaguette', 'Colmont, Marie', 'Flammarion - Père-Castor', 302, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (209, ' À table !', 'Cobb, Rebecca', 'Kaléidoscope', 361, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (31, ' Je ne suis pas comme les autres ', 'Coat, Janik', 'MeMo', 496, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (118, ' Les histoires de Léo et Popi : Lheure du lit', 'Clément, Claire - Gaudrat, Marie-Agnès', 'Bayard jeunesse', 239, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (208, ' La batterie de Théophile', 'Claverie, Jean', 'Gallimard jeunesse', 175, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (80, ' Cherche la petite bête !', 'Chedru, Delphine', 'Naïve', 294, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (207, ' Une chanson dours', 'Chaud, Benjamin', 'Hélium', 374, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (5, ' Un petit bouquet de poèmes', 'Charpentreau, Jacques (choix de) ', 'Hachette - livre de poche', 335, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (79, ' Où est qui ?', 'Charlip, Remy', 'MeMo', 286, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (30, ' Parapluie', 'Charlat, Benoît', 'Lécole des loisirs', 243, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (78, ' Petite Boîte Jaune', 'Carter, David A.', 'Mango jeunesse', 121, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (117, ' La chenille qui fait des trous', 'Carle, Éric', 'Mijade', 162, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (206, ' Roule Galette…', 'Caputo, Natha', 'Flammarion - Père-Castor', 303, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (29, ' Plic, plac, ploc', 'Bushika, Etsuko', 'Didier jeunesse', 248, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (151, ' Le panier de Stéphane', 'Burningham, John', 'Kaléidoscope', 381, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (116, ' Le petit bateau de Petit ours', 'Bunting, Ève', 'Lécole des loisirs', 108, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (205, ' Grand Loup & Petit Loup', 'Brun-Cosme, Nadine', 'Flammarion - Père-Castor', 222, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (4, ' Enfantines', 'Bruley, Marie-Claire - Tourn Lya', 'Lécole des loisirs', 337, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (77, ' Alboum', 'Bruel, Christian', 'Thierry magnier', 380, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (150, ' Une histoire sombre, très sombre', 'Brown, Ruth', 'Gallimard jeunesse', 299, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (28, ' Berceuse du merle', 'Brouillard, Anne', 'Seuil jeunesse', 116, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (204, ' Dis-moi loiseau…', 'Brière-Haquet, Alice', 'Thierry Magnier', 458, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (27, ' Jaime la galette', 'Bourre, Martine', 'Didier jeunesse', 397, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (149, ' Bon appétit ! Monsieur lapin', 'Boujon, Claude', 'Lécole des loisirs', 191, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (26, ' La trompe de léléphant', 'Bosquet, Alain', 'Rue du monde', 199, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (148, ' Sam et son papa', 'Bloch, Serge', 'Bayard jeunesse', 166, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (3, ' 365 contes pour tous les âges', 'Bloch, Muriel (choix de)', 'Gallimard jeunesse', 411, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (203, ' Le loup et la mésange', 'Bloch, Muriel', 'Didier jeunesse', 180, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (202, ' Paul et son ours', 'Blanchard, Arlène', 'Mijade', 127, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (76, ' Le balcon', 'Bertier, Anne', 'Grandir', 417, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (25, ' Le livre de lété', 'Berner, Rotraut Susanne ', 'La joie de lire', 396, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (24, ' Dans sa maison, un grand cerf', 'Bauer, Jutta', 'Lécole des loisirs', 413, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (201, ' Oh ! La belle lune', 'Battut, Éric', 'Didier jeunesse', 383, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (23, ' ABC 3D', 'Bataille, Marion', 'Albin Michel jeunesse', 285, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (115, ' Sur le chantier', 'Barton, Byron', 'Lécole des loisirs', 488, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (147, ' Il ne faut pas habiller les animaux', 'Barrett, Judi ', 'Lécole des loisirs', 242, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (200, ' Ferme les yeux', 'Banks, Kate', 'Gallimard jeunesse', 269, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (146, ' Le Bonhomme de pain dépice', 'Aylesworth, Jim', 'Circonflexe', 449, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (75, ' Loup y es-tu ? ', 'Auzary-Luton, Sylvie', 'Kaléidoscope', 375, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (114, ' Bonne nuit Petit Ours Brun !', 'Aubinais, Marie et all.', 'Bayard jeunesse', 118, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (113, ' Que non, je mhabille !', 'Ashbé, Jeanne', 'Pastel', 138, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (22, ' Devinettes en petits morceaux', 'Armellini, Chiara', 'La Joie de lire', 285, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (2, ' Anthologie de la comptine traditionnelle francophone (avec Cédé)', 'Arleo, Andy - Caëtano, Marie Laurentine (coordination de lédition) - Guichard, Rémi', 'Eveil et découvertes', 425, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (74, ' Choisis ton masque', 'Anno, Mitsumasa', 'Lécole des loisirs', 161, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (199, ' Oskar le coq', 'Angeli, May', 'Thierry Magnier', 127, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (198, ' Loiseau à deux becs', 'Alzial, Sylvain', 'MeMo', 148, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (73, ' Petits points rouges', 'Altan', 'Lécole des loisirs', 165, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (197, ' Naie pas peur, Teddy ! Je te protègerai des bêtes sauvages', 'Alexander, Martha', 'Pastel', 385, true);
INSERT INTO public.book (bookid, bookname, author, editeurs, nbpage, dispo) VALUES (1, ' Qui a vu lours ? (kamishibaï)', 'Alessandrini, Jean ', 'Callicéphale', 184, true);

INSERT INTO public.usertable (userid, pseudo, password, gender, mail, role, salt) VALUES (108, 'Protected', 'pdzpn0PwwN/64ZNXaqsmz4K7QQm9ne9vJa9Nebjc+70=', true, 'max.leboiteux@gmail.com', 2, 'vKxRfKy95bAkLqk8nFAo1jqybG9x25');
INSERT INTO public.usertable (userid, pseudo, password, gender, mail, role, salt) VALUES (112, 'Crashtest', 'ADIF+ba6x46Bd/PCC9VKz8ZY03ACCJIeG39MwZl134w=', true, 'testmynewnew@gmail.com', 1, 'zsV23grmLo2I3l3ikj8KAO4j7kbGHp');

INSERT INTO public.rentbook (rentid, user_id, book_id, reload, returnbook, create_at, end_at) VALUES (109, 108, 250, false, false, '2018-09-07', '2018-09-07');
INSERT INTO public.rentbook (rentid, user_id, book_id, reload, returnbook, create_at, end_at) VALUES (110, 108, 249, false, false, '2018-09-07', '2018-09-08');
INSERT INTO public.rentbook (rentid, user_id, book_id, reload, returnbook, create_at, end_at) VALUES (111, 108, 195, false, false, '2018-09-07', '2018-09-08');
INSERT INTO public.rentbook (rentid, user_id, book_id, reload, returnbook, create_at, end_at) VALUES (114, 112, 145, false, true, '2018-09-11', '2018-10-11');
INSERT INTO public.rentbook (rentid, user_id, book_id, reload, returnbook, create_at, end_at) VALUES (113, 112, 69, true, true, '2018-09-11', '2018-11-14');
INSERT INTO public.rentbook (rentid, user_id, book_id, reload, returnbook, create_at, end_at) VALUES (115, 108, 145, false, false, '2018-09-13', '2018-10-13');


