version: '2'
services:
  myerp.db:
    image: postgres:9.4
    ports:
      - "192.168.0.17:5432:5432"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_DB=libraryDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Toysrusse
      
