version: '2'
services:
  myerp.db:
    image: postgres:9.4
    ports:
      - "192.168.0.14:5432:5432"
    volumes:
       - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=libraryDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Toysrusse